### ISSUE TITLE
Wechsel/Auswahl von Kontos im Kontomanager

### ISSUE THREAD

**Issue by louglazar** [chkockle/FinanceDashboard#1]
[utb_Accounts.txt](https://github.com/chkockle/FinanceDashboard/files/3907470/utb_Accounts.txt)
  Debug im Module md_UserFormSubsAccounts - Fill Details () - In .accounts_ComboBox_Type.value = .accounts_ListView_ledger.SelectedItem.SubItems(2)

passiert nur bei Com Giro und Riester Account Select

**Comment by chkockle** [comment]
Com Giro: Leerzeichen beim typ des Kontos
Riester: Typ „Bonds“ gibt es nicht bei den Konten. 

Du hast manuell das json file manipuliert und nicht valide Kontentypen eingetragen. Bitte direkt in der DB bereinigen.
